server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://101.35.169.211:3777/library_management_system?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  data:
    redis:
      host: 101.35.169.211
      port: 6379
      password:
      jedis:
        pool:
          # 连接池最大连接数，若为负数则表示没有任何限制
          max-active: 8
          # 连接池最大阻塞等待时间，若为负数则表示没有任何限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8

mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

# 配置swagger文档的访问路径
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

oss:
  accessKey: "I5ar_vimHClfBgXWgapXE2I1-YOvOIY5ZU6xhgs9"
  secretKey: "VBaGIjayq0gsEai25onaajdJ3GRErAX_PgtdEkv8"
  bucket: "wk-blog123"
  baseUploadUrl: "http://s1fdhcbff.hd-bkt.clouddn.com/"